SRC_monkey = src/monkey1.0.cpp
SRC_rmonkey = src/rmonkey1.0.cpp
PROG = monkey rmonkey
CC = g++

all: ${PROG}

monkey : ${SRC_monkey} 
	${CC} -o Monkey ${SRC_monkey}



rmonkey : ${SRC_rmonkey} 
	${CC} -o rMonkey ${SRC_rmonkey}


